/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 03.06.2026 22:21:32

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1440;
#else
constexpr int kTensorArenaSize = 416;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,39 } };
const TfArray<1, float> quant0_scale = { 1, { 0.82306265830993652, } };
const TfArray<1, int> quant0_zero = { 1, { -126 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[6] = { 275, -250, -22, -110, 147, 3, };
const TfArray<1, int> tensor_dimension1 = { 1, { 6 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00059582263929769397, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[6*30] = { 
  59, 75, -7, 63, -82, 46, 13, 84, -85, 32, -86, 98, -81, 56, -93, 46, 3, -105, 17, -99, -69, 50, 71, 64, 26, -86, 1, -1, 10, 75, 
  51, -17, -81, 22, 29, -11, -70, -32, 66, -47, 52, 26, 11, 94, -14, 45, 92, -59, 66, -51, 30, -71, -50, -50, 7, -32, 5, -55, -24, -74, 
  -73, 102, -84, -73, 71, 88, -88, -30, 11, -9, 54, 27, -87, 29, 55, 20, -69, 72, 6, 47, 4, -21, 38, -31, -10, 19, 49, -59, 14, 71, 
  9, -72, 40, -69, 75, -29, -115, 46, -88, 29, 127, -13, -82, -64, -56, -92, 11, -54, -95, 73, -62, 54, -51, -50, 52, -102, -100, 45, -87, -89, 
  59, -49, -21, -75, -26, 52, 111, 22, 119, 29, -55, -38, 5, 93, -64, -67, 30, -68, -92, 23, -57, -52, -57, 48, -52, -21, 27, -18, 8, -48, 
  -22, -28, -92, -47, 23, -86, 76, -1, -35, 81, 47, -60, 93, 62, 11, 26, -15, 82, 127, 53, -96, 66, 25, -74, -121, -32, -111, 32, 83, 43, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 6,30 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0040391352958977222, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[30] = { 33, 81, 145, -49, -109, -42, 567, 511, 7, 160, -257, -11, -96, -114, -77, 110, -88, 95, 137, -105, -246, -11, -95, 33, -74, 124, 206, 78, 1, 140, };
const TfArray<1, int> tensor_dimension3 = { 1, { 30 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00064113468397408724, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[30*60] = { 
  14, 4, 40, -20, 33, -31, -24, -34, -33, 28, 24, -28, -19, -28, -5, -37, -1, -28, 0, -16, 25, 8, -11, 4, 34, -35, -2, -20, 19, -23, -11, 40, -37, -30, -41, -2, 8, -23, 39, -25, -22, 21, 27, 13, -40, -41, 25, -7, -33, -8, -39, 15, -7, 27, 32, 2, 27, -11, 18, -7, 
  -20, 23, -19, 7, 40, 29, -27, -21, 38, -11, 33, -30, -27, -1, -68, 1, 37, 16, 5, 9, -3, 16, 16, 17, 33, -58, 13, 18, 0, -5, 4, -27, 20, -40, -62, -59, -4, 9, -20, 29, 0, -17, -26, -24, -19, -64, 37, -28, -17, 31, 17, 2, 37, -7, -5, -52, 15, 1, 50, 4, 
  -8, 36, -13, 0, 7, -13, -25, 24, 57, 22, 9, 17, -36, 3, 66, 23, 37, -21, 30, -10, -35, 8, 55, 10, 6, -18, 27, -35, 15, 16, 33, -14, 33, -2, -1, -5, -9, -28, -19, -18, -32, -62, -25, -22, -39, -27, -40, 23, -13, 20, -25, 37, -12, -26, 33, 0, -46, -24, 40, -22, 
  21, 0, -21, 15, -28, -26, 29, 31, 16, -8, 19, 22, -42, -15, -18, 12, -31, -9, -30, -37, -25, -22, -20, 24, -16, -8, -23, -51, 21, -25, -19, -32, -26, 0, -22, 29, 34, 30, 16, 24, -43, -45, 35, -31, -38, -19, 23, -6, -14, -2, -3, 25, -24, -17, 16, 2, -23, 58, -21, -28, 
  -16, -14, -13, 24, -3, -29, 24, -3, -17, 42, 10, 3, -8, -3, 19, -32, 38, -11, 12, 15, -30, 23, -22, -29, -4, -19, 12, 9, -3, 22, 27, -25, -6, 35, 54, 30, -1, -17, -29, -35, -37, 68, 32, 25, -13, 16, 37, -38, 73, 33, -1, 25, -23, -27, -13, 42, 22, 12, -38, -28, 
  -31, 17, -2, -22, -23, -29, -30, 31, -18, -4, -42, -45, -31, 33, -37, 21, -18, -10, 31, -6, 35, -37, 6, -2, 19, 28, -14, -27, -29, -31, -2, 2, 9, -17, -3, 1, -14, 2, -11, -6, -38, -37, 23, 28, 16, -15, -21, 10, -32, -42, -26, 32, 14, 39, 14, 23, 9, 4, 0, 30, 
  33, -25, 4, -25, -21, 4, -28, -11, 38, 28, -33, -25, 9, -5, 52, 4, -25, 9, -6, -34, 1, -1, 27, 18, 6, -7, 50, -5, -12, -18, -18, 50, 31, -23, 79, 2, -17, -33, -39, -28, -33, 57, 5, -52, -43, 18, -4, 9, 75, -36, 34, -38, 6, -1, -7, 109, -12, 75, -5, 43, 
  -5, 23, 31, -23, 67, 22, 11, 21, 72, 95, -12, -27, -24, -21, 37, -18, 25, -36, -36, -11, 28, 30, -20, 11, -29, 1, 62, -60, -35, -35, 6, 31, 35, 15, -61, 21, -23, 6, 19, 0, -31, -9, 8, -5, -1, -17, -35, -16, -48, -50, 14, 41, -55, -16, -21, 8, -62, 70, 37, 35, 
  22, 13, -39, -2, -31, 33, -23, -35, 20, -127, -17, -2, -15, 58, 56, 7, 25, 56, -4, 31, 40, 12, -1, 18, 24, 43, -13, 32, 33, -22, -12, 35, 24, -26, 19, 3, 2, 19, -10, 0, -20, -59, 11, 35, 0, -44, 38, -25, -21, 6, -38, -35, -58, -37, -41, 87, -14, 30, -13, 17, 
  16, 0, -7, -39, -22, -12, -5, -41, 23, 19, 11, -18, 12, 12, 23, 19, -6, -15, 6, -26, 5, 22, -35, -8, 22, 33, 37, -43, 27, 24, -3, 10, -28, -26, 36, 28, 6, 1, 20, -23, -46, 45, -2, -44, 0, 60, 9, -28, 12, -32, -18, 1, 27, 21, -20, 62, -49, 51, -3, -41, 
  -28, 37, -37, 27, 43, 9, 21, 23, 5, 6, 33, 43, -13, 21, -22, 16, 29, 1, -35, -37, -17, -11, 49, -13, 10, 27, -10, 23, 26, 7, -20, 5, 14, -5, -32, -28, -37, 42, 17, 5, -3, 41, 2, 53, -10, 56, -31, 13, 69, 24, -8, -13, -19, 24, 17, 18, 11, -64, -2, -41, 
  -41, 19, -34, -23, 23, -24, -13, -34, 20, -4, -12, 2, 7, 4, 1, 27, 15, -25, 12, 26, -6, 22, -11, -29, -16, -30, -46, 0, -20, -31, 1, 13, -16, -37, -40, -22, 21, -37, 30, 22, -7, -19, 10, -26, -23, 21, 23, -19, -18, 10, 16, 4, 26, 38, -25, 15, -5, -33, -8, -15, 
  -34, -17, 7, 6, -37, 22, -32, -2, -17, 0, 18, 4, 28, 22, 25, -39, 6, 27, 0, 16, -41, -11, 38, -29, -21, -16, -51, -33, -25, -22, 12, -13, 3, -38, 35, 30, 39, -31, 16, 34, -16, 43, -33, -23, -29, -22, 30, -25, 3, -41, -22, -42, -24, 13, 21, -37, -21, -29, 5, 15, 
  5, -24, -16, 27, -41, -18, 21, -25, -45, -16, 28, 5, -15, -26, -3, -5, 5, -19, 35, -19, 22, -37, -24, -31, -4, -47, 21, 6, 28, -25, -25, 28, 28, -49, -30, 5, -11, 14, -10, -8, 18, 29, -7, -13, 31, 11, -31, -44, -18, 3, 28, 30, 30, 17, 24, 6, 25, -23, -5, -42, 
  21, -29, 10, 36, 7, -13, 14, 31, -68, -9, 17, 21, -32, -7, -41, -4, 4, 39, 28, 8, 13, -11, 30, 43, 10, 14, 8, -8, 21, -39, 34, -33, 40, -1, -56, -44, -20, -33, 33, -41, -6, 30, -36, 7, 31, -24, 7, -3, 66, -27, 35, 17, 68, -42, 21, 21, -43, -43, 42, 42, 
  25, -10, 28, 19, 15, -18, -4, 23, 25, 22, 23, 15, 18, 21, 5, -34, -6, -24, -38, 12, 19, 18, 24, -13, 21, 15, -33, -21, -24, -7, -12, -6, 6, -36, 1, -26, -26, -29, -5, 18, -30, 29, -39, -27, -25, -4, 34, -2, 50, 2, 29, 22, -23, -8, -6, 19, 16, 31, 23, -32, 
  17, 28, -12, 25, -30, 24, 0, 0, 62, -67, 18, 24, -26, -11, 92, 15, -41, 29, -13, -11, -12, 20, 15, 32, 12, 50, -125, 18, 28, -29, 10, 59, 4, 4, 47, -7, 3, -4, -36, -8, -15, -31, 22, 43, 26, -8, 19, -1, -40, 21, 4, 24, -38, 38, -37, 30, 13, -22, -8, 37, 
  32, -3, -39, -24, -12, 14, 23, -23, 32, 8, -10, -45, 56, 22, 5, -26, -15, -16, -39, -24, -36, -34, -4, -27, -37, -20, 12, 27, -2, 22, -3, -22, 21, -21, -14, -31, 30, 29, 5, 22, -43, 61, -3, -21, -11, 78, 23, -39, 32, -10, 33, -33, 12, -21, 9, 54, -5, 46, 11, 14, 
  14, 34, -9, 28, -36, -35, -20, 11, -20, 39, 34, -43, 70, -47, -3, 14, 31, -12, 15, 11, 26, -25, 26, 24, -9, -36, 21, -43, -39, -18, -8, 9, 16, -33, 27, 22, -13, 28, 18, 20, -44, 71, -39, -25, -16, 50, -36, -27, 64, -25, 10, -36, 42, -11, -13, 56, 28, -18, 15, -20, 
  -25, 29, 4, -31, -24, -14, 19, -35, -37, 21, -31, -37, -11, 30, -48, -12, -6, 24, 27, -35, -28, -24, -5, -40, 32, -34, -7, 16, -10, -3, -31, 14, -33, -12, 42, -21, -33, -21, 33, -15, 27, -9, 13, 30, 7, -33, -37, 16, 53, -11, 29, -29, -8, 19, -11, -42, -8, -31, -26, 29, 
  -24, 4, -2, 13, -2, -4, 35, 9, 6, -38, -25, -25, 18, 22, 5, 20, -23, 43, -2, 24, 15, 27, -36, 14, 29, 22, -95, -5, 10, 11, -6, -28, -15, 13, -42, 20, 25, 27, -8, -24, 43, 2, 32, 7, 36, -15, 4, -13, -17, -26, -30, 17, 30, 34, 15, -4, 55, -41, 19, 37, 
  24, -14, -33, -21, 57, 7, -1, 19, -2, 57, -24, -9, 38, 17, -63, -19, -36, -18, 14, -29, 16, -3, 31, -14, 9, 15, 46, -48, -1, -19, -18, 21, -30, 36, -26, 35, -3, 24, 6, -16, 21, -5, -24, -30, -16, 1, 30, 24, 14, 35, 16, -40, -1, -40, 5, -43, -19, 33, 8, -10, 
  -1, -20, -15, 11, 4, -41, -26, -41, -14, 75, -19, 15, -48, -38, 6, -47, -15, 25, -20, -2, 29, -11, -40, -2, 34, -26, -4, -28, 33, -10, 11, -24, 14, 32, -55, -5, -7, -6, -3, 1, -23, 8, -39, -35, -13, 8, -48, 13, -10, -8, -30, -2, 11, -29, 15, -30, 23, 16, -47, 21, 
  33, 26, -10, 11, -6, -22, 34, -12, -2, -2, 17, -3, -2, 10, -46, 31, 23, 13, -20, 17, 4, -19, -28, 5, -27, 3, 31, 30, -41, -21, 0, -2, -3, -28, -15, 3, -37, -12, 25, 38, 21, -42, 28, -20, 33, -15, -32, -41, -71, -42, -18, -39, 24, 11, -23, -12, -11, 26, -14, 15, 
  -34, 24, -33, 32, 29, 53, -16, -29, 20, -9, -20, 45, -18, -37, -29, 32, -18, -31, -7, -5, -17, -6, 40, 11, 40, 48, -6, -50, 33, -21, -12, 14, -38, 53, -25, 16, -14, -5, 25, -14, -2, -61, -27, -17, 26, 21, -29, 14, -20, 46, -3, 52, -30, -40, -1, -7, 38, 18, 48, -37, 
  -25, -42, -41, 22, -14, 24, -49, -3, -46, -66, -2, 21, -40, 3, -50, -21, 30, 45, 20, 16, -31, 27, 13, -24, 16, -59, 27, 45, 5, 40, 12, -17, 7, 5, 64, -58, -20, -25, 26, 22, -16, -27, -43, 24, -20, -9, -8, 25, -27, 13, -38, 5, 9, 0, 31, 38, -11, -17, 20, 51, 
  -21, 27, -9, 9, -2, -7, -16, -35, -39, 12, -8, -13, 15, 61, -35, 21, 28, 42, -39, 41, -30, 34, -31, 22, -28, -33, 56, 6, -31, 35, -19, 3, 31, 9, -5, -34, -36, 6, -15, -17, 38, -32, -35, 24, 0, -22, -13, 34, -39, -21, -10, -19, 38, 24, 19, -6, -47, 4, -22, 2, 
  17, 32, 41, 37, -24, -3, 7, -22, 12, 18, 35, -29, 50, 12, -13, -20, -37, -36, 33, 22, 30, 4, 48, 8, 16, -31, 28, -51, 11, -21, -2, -4, 3, 39, 3, 30, -16, -40, -21, -23, 29, -2, 14, -21, -32, 54, -5, -39, 27, -6, -34, -23, -27, -2, -17, 31, 22, 29, 7, -2, 
  20, 13, -11, 0, -20, 15, 0, 22, 7, -13, -1, -37, -18, -25, 35, 29, 13, -41, 2, 28, 5, -44, 3, -6, 5, 20, 11, -41, 3, -34, -8, -26, 0, -27, 37, 29, -12, -28, -17, -31, -25, 67, -36, -45, 36, -11, 10, 12, 37, -1, 16, -36, -30, 0, 31, 34, -44, 25, -19, -13, 
  -6, 37, 28, 10, 23, 23, 28, 4, -30, -24, -19, 33, -17, 15, -110, 32, -1, 4, -31, 34, 20, 6, -51, 19, 15, -39, 15, -3, -15, -36, -7, 24, -13, -31, -38, -17, 18, 17, 25, 2, -25, 17, -29, -12, -15, -31, 13, 0, -18, 21, -40, 7, 50, 13, 30, -53, -60, 21, 36, 11, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 30,60 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0062064067460596561, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[60] = { 0, -1, 0, -10, -9, -7, -11, 0, 4, 10, -10, -14, 10, 3, 0, -14, -1, -1, -1, 0, -5, -10, 0, -7, 0, -14, 13, 1, -10, -9, -16, 2, 0, 1, 16, -7, -1, 0, 0, 0, -13, 14, -11, -9, -15, 14, -8, -8, 15, -8, 0, -11, 1, -2, -6, 13, -13, 12, 5, 1, };
const TfArray<1, int> tensor_dimension5 = { 1, { 60 } };
const TfArray<1, float> quant5_scale = { 1, { 0.0091310292482376099, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[60*39] = { 
  0, 18, 6, -17, -19, 19, -11, -6, -20, -11, 5, -18, -14, -14, -16, 18, -14, -20, -18, 16, 8, -15, 0, -3, -13, -12, -3, -1, -4, -3, 7, 18, 21, -9, 4, -9, -12, 6, -11, 
  -22, 4, 7, 19, 2, -12, 21, -3, 10, 15, -4, 20, -18, -11, 22, -5, 1, -3, -4, 17, -5, -4, 16, -7, 12, 17, -2, -23, 10, -16, 6, 4, -11, -20, -1, 10, -5, -20, -7, 
  14, -16, 13, -2, -16, 15, 0, -20, 3, 11, -11, -16, -19, -17, -20, -4, 8, -5, 11, 3, 20, 4, 5, -7, 2, -19, -11, -12, 2, 0, -15, -8, 7, 6, -11, -9, 2, 11, -14, 
  -25, 42, 31, -27, 3, -12, -3, 4, 6, 5, -18, -17, 17, 11, 15, -29, 11, 0, -1, -30, 14, 6, 5, -28, -19, 2, 6, 37, 14, -20, 12, -4, -21, -13, 9, -9, -1, -5, -6, 
  18, 48, 119, 10, -13, 8, -12, 26, -13, 11, 3, -20, 1, 19, 78, -61, 4, 16, -5, 9, -14, 9, -11, -9, 15, 13, -8, 68, 103, -46, -11, 14, 1, -21, -5, -13, -10, -8, 5, 
  -13, -3, 6, 3, -17, -6, -11, -24, 9, -9, -10, -18, 9, 11, 9, -30, -2, -5, 3, -9, 0, -23, -12, 5, 11, -20, 8, 12, 10, -13, -1, 11, -7, 8, 12, 0, 3, -7, 10, 
  3, -3, 13, -7, -4, -12, 13, -3, -17, -26, 6, -11, -28, 16, 21, -27, -5, 24, -1, 10, -21, -22, -27, -20, -14, 5, 2, 35, 13, -11, -21, 12, -18, -11, -8, -11, -19, 3, -3, 
  16, 19, 6, 18, -8, -21, -15, -14, -5, 6, 5, -19, -4, -8, 22, -2, -13, -6, -7, 15, -15, -16, 5, 22, -4, 4, -12, -22, 6, 10, -6, -12, -7, 20, -1, -8, 20, -18, 19, 
  16, -78, -100, -5, 13, -7, 34, 9, 20, 3, 18, 2, -29, 5, -127, 59, -34, -29, 11, 20, 11, 5, 22, -6, 5, -23, -8, -79, -61, 25, 14, -5, 25, -8, -1, 19, 1, 21, 19, 
  -6, -29, -23, -13, -7, 26, 27, 24, 30, 17, -2, 6, 20, 21, -7, -7, 17, 14, -3, 12, -8, 27, -10, 19, 29, -11, -16, 68, 16, -26, -1, 4, 8, -2, -14, 8, 17, -7, 25, 
  14, -13, 39, -4, 0, -22, -2, 3, 9, -15, -31, -15, -14, 6, 9, 19, 7, -12, 8, -18, -1, 5, -28, -3, -13, 11, 3, 16, 17, -10, -2, -20, -22, 1, -1, -19, 9, -10, -31, 
  -10, 0, 31, -18, 10, -1, 9, -14, -2, 1, -13, -21, -25, 11, -2, 3, -29, 19, 11, -13, 7, -15, 4, -15, -23, -4, 4, 33, -24, 3, 19, -27, -1, -17, 6, -3, -11, -6, -31, 
  -2, -6, -17, 14, 2, 24, 26, 21, 19, -3, -2, 28, 25, -6, -23, -8, 3, -23, -6, 15, 1, 22, 23, 23, 17, -14, -11, 7, 21, -5, -19, 12, 16, 3, 19, -10, 19, 1, -7, 
  -2, 47, 18, 8, 13, -15, -26, -14, -8, 18, 7, -20, 20, -17, 59, -41, 39, 20, 21, 11, 0, -24, 15, 19, 13, -9, 7, -26, 20, 29, 8, 15, -11, -10, 6, 8, -2, -18, -10, 
  20, -47, -104, 4, -8, -11, 19, 13, -16, -17, 24, 13, -28, -22, -122, 59, -46, -7, -20, 2, -5, 29, 18, 13, 18, 6, 4, -77, -83, 21, 12, 10, 19, 24, -7, -9, -16, 4, -20, 
  -9, -14, 5, 0, -7, 8, -2, 9, -5, -18, -4, 3, -9, 11, 31, -22, -23, -2, 0, 0, -8, -19, -5, 5, 10, 7, 8, -12, 39, -6, 1, 5, -27, 1, 11, -22, 13, -28, 4, 
  0, -1, -8, -19, 4, 7, 9, -13, 8, 16, 7, -14, 6, 0, 3, -17, -2, -2, -4, -5, -15, 1, 0, 20, -12, 11, -14, 20, -1, -14, 3, 3, 1, -11, -5, 15, -4, 5, -21, 
  -6, 22, -21, -3, -8, -9, 18, -12, -12, 6, -4, 4, 20, -23, 1, -8, -19, -13, 5, -20, 3, 19, -6, -9, 11, 4, 17, -46, -23, 20, 13, -12, 8, -21, 2, -25, 3, -10, -16, 
  -20, -22, -14, -8, -18, -13, -13, 17, -11, -7, 9, -21, 5, -8, -12, -3, -18, -18, 13, -15, -8, 16, 18, 18, 16, 6, -7, 9, 11, 2, -20, -8, 11, -14, 4, 0, 0, 2, -13, 
  -1, -11, 7, 15, 15, -9, -12, -20, -1, -9, -15, -14, -20, -3, 6, -18, -2, 10, 10, -18, -17, 8, -4, -13, -6, 7, -19, -2, -4, -2, -21, -5, -15, -13, 15, 14, -2, 17, 10, 
  -11, 17, -8, -4, -12, 0, -17, 12, 7, -22, 1, -26, 10, 0, 14, -19, -12, 15, 7, 14, -15, -10, 1, -1, -12, 9, 9, -19, 8, -21, -4, -8, 5, -7, 5, -14, -16, -5, 15, 
  -4, 10, 23, -17, 6, 13, -19, 15, 7, -9, 17, 12, -3, -10, 41, 13, 1, 9, -24, 15, 13, -10, -25, 17, -4, -7, 15, -17, 13, -6, 7, -2, -22, 2, -7, 12, -7, 18, 17, 
  0, 10, 21, -20, 7, 8, 9, 14, -3, -9, 15, -5, 0, 17, -14, -2, -6, 4, -15, 4, -6, -5, -11, 0, 19, -17, -12, 22, 10, -24, 17, 23, 11, -21, -16, 19, -4, 1, -18, 
  10, -9, 22, 14, 8, -19, 12, -17, 7, 15, 7, 11, -24, -19, 35, 4, 1, -16, -19, -11, 6, -16, -19, 11, -17, -8, 17, 20, -7, 2, 1, 15, -7, -10, -16, 1, 4, -4, 16, 
  4, -17, -5, -6, -10, 13, -5, -4, 1, -20, -14, -7, -20, 2, -8, 16, 15, -17, 21, 19, -18, 1, 22, -19, 8, -7, -9, 11, -13, 15, 1, 6, -5, -5, -6, -21, 7, -13, -2, 
  11, -71, -74, -37, 5, -31, 1, -20, -11, -18, -10, -6, -36, 11, -115, 46, -19, -3, 0, 10, -37, -5, 7, 12, -28, -20, 0, -77, -98, 33, 17, -12, -1, -12, -16, 11, -6, 0, -7, 
  -2, 53, 116, 12, 12, 2, 19, 8, 4, 26, -13, -6, 30, 1, 116, -47, 29, -10, 10, 15, 18, 10, 25, 12, 22, 26, -5, 92, 90, -24, -5, 6, -4, -3, -3, 9, 17, 21, 7, 
  -23, 54, 23, -7, -3, -8, 18, -11, 23, -21, 21, -8, 9, -7, 7, -2, 14, -1, -14, 14, -8, 10, -11, -14, 8, -6, 15, -10, -48, 26, -8, -16, -19, -6, -18, -11, -7, 5, -7, 
  15, -82, -94, -6, 7, 0, 2, 4, 7, 11, -28, -27, 1, -19, -83, 35, -21, -1, 0, -6, -19, 0, 7, -17, -28, -30, 9, -78, -63, 28, 4, 5, -3, -24, 5, -16, -18, -3, 10, 
  3, 11, 22, -28, -10, -10, -25, -2, 9, -7, -14, 6, 12, 4, -11, 18, -20, -8, -1, -27, -18, -8, -15, -21, -8, 15, 7, -16, 12, 11, 20, -5, -29, 6, -16, -32, 0, -18, 7, 
  -6, -5, 18, -30, -22, -13, -9, -31, -16, 4, -30, 9, -28, 4, 0, 8, -1, 1, 9, -7, -3, -7, -2, 5, -21, -6, 9, 22, 30, -24, 22, -16, -5, 6, -5, -12, -11, -6, -10, 
  5, -72, -88, 24, 29, -9, 7, 12, 11, 22, -1, 7, -5, 0, -90, 32, -14, -1, 8, 6, 4, 22, -7, -17, -16, 4, -2, -72, -92, 19, -1, 1, 15, -1, 22, 1, -26, 13, -14, 
  -21, 14, -21, -5, 12, 3, -6, -14, -7, 19, 5, 14, -14, -2, -11, 21, 22, -22, -21, -4, -16, 4, 9, 0, 14, -8, -19, 18, 17, 1, 20, -15, 2, -15, 7, -1, 4, 1, 4, 
  -20, 19, 22, 4, 3, -21, -7, 1, -20, -2, -20, -2, 0, 24, -24, 4, 14, -13, -6, 13, -5, 16, 19, -17, -3, -10, -11, 2, 7, -4, 4, -20, 22, 5, -15, 1, 10, -12, 13, 
  -13, 13, 10, 25, 14, -8, -7, 1, 0, 28, 0, 7, 17, -22, 11, -11, -5, 0, -4, 30, 19, 13, 24, 13, 1, 3, 2, -22, -31, -9, 7, -7, 28, -9, 28, 24, -2, 33, 24, 
  13, -85, -75, -12, 8, -3, 15, -30, -3, -9, -11, -8, -36, 7, -92, 25, -9, -2, -21, -17, -24, 6, -18, -23, 13, -20, 1, -50, -50, 13, 25, 13, 6, 11, -8, -2, -24, -25, -21, 
  -15, 17, -17, -20, 12, -18, -8, 7, -8, -16, -1, -7, -20, -1, 15, 18, -10, -5, -22, 13, 18, -16, -9, -19, 18, -11, 3, -23, 13, 21, 22, 2, -8, -4, -4, 9, -14, 14, 6, 
  11, 16, 18, -8, 16, -15, -12, -16, -17, -2, -17, 2, -12, -21, -7, 2, 11, 20, -16, -5, -17, -5, 1, 17, 20, -18, -17, -19, 20, 5, 21, 16, -8, 19, -13, -18, -22, 17, 7, 
  -6, 11, -2, -20, -16, 1, 8, -12, -19, -20, -10, 22, -15, -16, 11, 22, -20, 10, -16, -6, -12, 11, -18, 14, -10, 20, 8, 19, 4, -1, 17, -16, 5, -22, 2, -11, 12, -22, -16, 
  17, -4, -3, -18, 0, -1, 6, 17, 1, 8, 3, 2, 5, -14, 12, -21, 1, -19, -11, -15, 15, -17, -15, -21, -3, -18, -10, -1, 8, 6, 3, 6, -16, -7, -17, -21, 13, -19, 3, 
  -5, -14, -10, -2, -5, 8, 15, -4, -17, -26, 6, 2, -12, 1, -51, 38, -22, -18, 14, 9, -4, -18, 13, -24, -11, 1, 8, 22, -40, -24, 0, -28, -22, -29, -12, -5, 9, 7, -18, 
  18, 4, 12, 14, 7, 21, 6, 6, 6, -6, 28, 1, 14, -14, 7, -13, -9, -7, -12, -9, 0, 9, 21, -4, 11, -5, -9, 7, -5, 1, 14, 21, 12, 29, -7, -5, 2, 14, 14, 
  -19, -91, -52, -3, -2, 5, 23, -31, 15, -22, 6, -15, -5, 9, -89, 47, -19, -16, -6, -7, -15, 14, -14, -27, -13, -2, 4, -55, -82, 12, 23, 4, 1, -26, 7, 7, -25, -23, 0, 
  -13, -27, -49, 8, 6, -18, -15, -19, -20, 10, 13, -4, -9, 12, -43, 34, -36, -28, -26, -4, 12, -20, -20, -17, -3, 11, 3, -45, -59, 2, -2, -17, 12, -8, -14, -13, -30, 11, -28, 
  -3, -53, -68, -9, -12, 3, -8, -19, 6, -27, 9, -23, -14, -1, -60, 42, -16, -19, 2, 6, 6, 7, -33, -5, -3, -22, 8, -58, -47, 2, 21, -13, -27, -31, 11, -18, -31, -12, -22, 
  5, -8, -6, -4, -5, 14, -11, -2, 14, 30, 23, -15, 16, 12, -14, -10, 28, -3, 15, 8, 21, 6, 24, -4, -17, 3, -20, 29, 4, 9, -12, 5, 5, 13, 10, -9, 4, 18, 17, 
  -15, -11, 18, -9, 1, -18, -17, 9, 15, -2, -7, 7, -23, -2, 19, -22, -19, 7, -5, -15, 10, -2, -22, 13, 1, 11, 10, 21, 34, -21, -12, -27, -26, -19, 14, -21, -6, -29, 6, 
  -2, 22, 11, 17, -11, -17, 9, -6, -12, -9, -2, -28, 11, 4, 26, -18, -15, 12, -24, -29, 6, -2, -16, -2, -7, 8, 10, 11, 27, -19, 1, -16, -7, 6, -11, -27, -19, 2, 10, 
  16, 14, 0, 18, -3, 0, 30, 19, 25, -9, 6, 2, -6, -11, -21, -2, -9, -10, 12, 0, 28, -12, 22, 2, 1, -2, -13, -6, -2, 24, -21, 7, 18, -5, 10, 11, -1, 18, 15, 
  -19, -9, -17, -19, -4, 9, -7, 16, -4, 7, -21, 1, -9, 15, 5, 19, 2, -25, 10, 4, -17, -7, -17, 12, -7, -12, 4, 23, 14, -12, -11, 14, -22, -22, -4, -14, 5, -17, 11, 
  10, -9, -1, 7, 10, 0, -19, 17, -10, 15, -17, 19, -17, -3, -7, -21, -7, -1, -14, -4, 14, -21, 10, 2, 0, -14, -9, -15, -8, -11, 10, 1, -20, 13, 11, -20, -5, 11, -6, 
  15, -72, -21, 16, 9, -15, -8, -11, 4, 1, -7, -13, -8, 13, -19, 30, -33, -2, 3, -23, -9, 10, -9, -6, 11, 6, -3, 3, -3, -2, -21, -4, -12, -10, 5, 14, -16, -3, -31, 
  -5, 62, 77, -15, -3, -6, 1, 21, -1, -8, -24, 15, -6, -1, 82, -47, 41, 15, -13, 3, -12, -5, 2, -12, 8, 24, 1, 90, 65, -5, -11, -16, 13, 12, -6, 19, 8, -13, -8, 
  -14, 23, -3, 4, -3, -5, -18, -9, -16, 0, -18, 4, 16, 9, 18, 11, 6, -9, 2, -5, -5, 15, 3, -6, 9, -12, -10, -9, 14, -22, -13, -17, -1, 18, -15, -4, 12, 5, 10, 
  -22, 59, 88, -23, -21, -2, 5, 16, -11, -14, -18, -20, 21, 10, 90, -67, 16, 14, 16, -24, -15, 6, -10, -20, 14, 5, 2, 45, 90, -14, -16, -4, 10, 14, -28, -25, -10, 4, 17, 
  -13, 47, 13, 12, -6, 19, -15, 19, 2, -4, 3, 14, 18, -18, 1, -8, 13, 6, 27, 26, 10, 15, 8, 26, 15, 17, -5, -23, -28, 39, 4, 25, 20, 29, 27, 15, 16, 15, 4, 
  -7, -85, -60, -19, -13, -20, -17, -22, -11, 9, 11, -20, -28, -1, -94, 42, -24, -22, -13, -17, -24, 12, -8, -11, 8, -9, 6, -27, -78, -6, 27, -21, 13, -11, 15, 13, -2, -27, -17, 
  24, -24, -1, 32, -13, 14, 24, 29, -5, -6, 10, 32, 21, -10, 28, 12, -3, 3, 22, -3, 18, 20, 17, 0, 20, -11, -13, 8, -1, 15, -26, 19, 30, 18, -4, 32, -10, 10, 23, 
  8, 59, 74, 0, -6, -9, -15, 25, -2, -15, -14, 21, -5, 2, 95, -46, 27, 1, -10, 12, -7, -17, 6, 14, -16, 12, -1, 59, 98, -41, -7, -11, 21, 23, -14, -12, -6, -13, 13, 
  -3, 8, 13, 16, -10, -19, -11, -19, -14, 16, 19, 7, 2, -22, -7, 6, 3, -2, 10, 17, -19, -4, -18, 13, -7, -21, 14, -55, -7, 14, -4, -19, 21, 16, -3, -18, 20, -14, -2, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 60,39 } };
const TfArray<1, float> quant6_scale = { 1, { 0.011093965731561184, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,60 } };
const TfArray<1, float> quant7_scale = { 1, { 0.10330207645893097, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,30 } };
const TfArray<1, float> quant8_scale = { 1, { 0.14751242101192474, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,6 } };
const TfArray<1, float> quant9_scale = { 1, { 0.29782223701477051, } };
const TfArray<1, int> quant9_zero = { 1, { -13 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension0, 39, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 24, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 180, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 120, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 1800, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 240, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2340, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension7, 60, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 64), (TfLiteIntArray*)&g0::tensor_dimension8, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 6, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1015537_4_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1015537_4_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1015537_4_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1015537_4_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1015537_4_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
