################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (14.3.rel1)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
CC_SRCS += \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.cc \
../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.cc 

CC_DEPS += \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.d \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.d 

OBJS += \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.o \
./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.o 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.o Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.su Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.cyclo: ../Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/%.cc Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/subdir.mk
	arm-none-eabi-g++ "$<" -mcpu=cortex-m4 -std=gnu++14 -g3 -DDEBUG -DUSE_HAL_DRIVER -DSTM32F446xx -c -I../Core/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc -I../Drivers/STM32F4xx_HAL_Driver/Inc/Legacy -I../Drivers/CMSIS/Device/ST/STM32F4xx/Include -I../Drivers/CMSIS/Include -I"/home/ivysson/STM32CubeIDE/workspace_2.1.0/Projeto final/Middlewares" -O0 -ffunction-sections -fdata-sections -fno-exceptions -fno-rtti -fno-use-cxa-atexit -Wall -fstack-usage -fcyclomatic-complexity -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Middlewares-2f-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels

clean-Middlewares-2f-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels:
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/activations_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/add_n.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/arg_min_max.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/assign_variable.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_matmul.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/batch_to_space_nd.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_args.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/broadcast_to.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/call_once.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cast.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ceil.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/circular_buffer_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/comparisons.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/complex_abs.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/concatenation.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.d
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/conv_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/cumsum.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depth_to_space.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/depthwise_conv_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/dequantize_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/detection_postprocess.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/div.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elementwise.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/elu.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/ethosu.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/exp.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/expand_dims.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fill.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_div.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/floor_mod.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.cyclo
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/fully_connected_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/gather_nd.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/hard_swish_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/if.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_runner.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/kernel_util_micro.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2_pool_2d.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/l2norm.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/leaky_relu_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/log_softmax.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logical_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/logistic_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/lstm_eval.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/maximum_minimum.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.o
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/micro_tensor_utils.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mirror_pad.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_interface.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mli_slicers.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/mul_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/neg.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pack.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pad.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/pooling_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/prelu_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/quantize_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/read_variable.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/real.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reduce_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/reshape.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.o
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_bilinear.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/resize_nearest_neighbor.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/rfft2d.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/round.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scatter_nd.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buf_mgr.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/scratch_buffers.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/select.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/shape.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/slice.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/softmax_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_batch_nd.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/space_to_depth.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/split_v.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squared_difference.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/squeeze.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/strided_slice.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.d
	-$(RM) ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/sub_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/svdf_common.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tanh.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tile.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/topk_v2.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/transpose_conv.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/tree_ensemble_classifier.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unidirectional_sequence_lstm.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/unpack.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/var_handle.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/while.su ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.cyclo ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.d ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.o ./Middlewares/edge-impulse-sdk/tensorflow/lite/micro/kernels/zeros_like.su

.PHONY: clean-Middlewares-2f-edge-2d-impulse-2d-sdk-2f-tensorflow-2f-lite-2f-micro-2f-kernels

